title: Maria & Chris 
description: Wedding Information
markdown: kramdown
theme: minima  

header_pages:
  - index.md
  - the-day/index.md
  - the-dinner/index.md
  - travel-info/index.md
  - pictures.md
  - gifts.md

navbar_pages:
  - /index.md
  - /travel-info/index.md
  - /the-day/index.md
  - /the-dinner/index.md
  - /img/index.md
  - /gifts.md

exclude:
  - archive/